name: Automated documentation from code into docs folder

on:
  pull_request:
    branches:
        - 'master'
    types:
      - closed


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pydoc_markdown
    - name: Run Documentation as code
      run:
        python -m build.document_from_code
    - name: Commit changes to the master branch
      run: |
        SRC_PATTERN="./docs/*.md"
        git config user.email "DocUCode@westerlymerlin.internal"
        git config user.name "DocUCode"
        git add SRC_PATTERN
        if git diff --cached --name-only | grep --quiet "$SRC_PATTERN"
        then
          echo "No changed documentation to update"
          exit 0
        fi
        git commit --message "DocUCode Automated documentation from code"
        git push origin master
      env:
        GH_TOKEN: ${{ secrets.ACTIONSECRET }}
